apiVersion: v1
kind: Service
metadata:
  name: {{ include "sptFika.fullname" . }}
  labels:
    {{- include "sptFika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: server
      port: {{ .Values.service.serverService.port }}
      protocol: {{ .Values.service.serverService.protocol }}
      targetPort: {{ .Values.service.serverService.port }}
    - name: headless
      port: {{ .Values.service.headlessService.port }}
      protocol: {{ .Values.service.headlessService.protocol }}
      targetPort: {{ .Values.service.headlessService.port }}
  selector:
    {{- include "sptFika.selectorLabels" . | nindent 4 }}
